### ISSUE TITLE
Getting "TypeError: 'encoding' is an invalid keyword argument for this function 192-168-1-103" in my terminal, and no images....

### ISSUE THREAD

**Issue by JohnnyDeadwax** [webscraperio/image-downloader#11]
Hi guys,
Total newb here, (this would be maybe 10th time I've ever opened terminal...lol)
I have downloaded/installed latest version of Python(3.12.0), I have my .csv file in the right place, it has the correct columns, and is with the "image-downloader.py" file. But I don't get any images downloaded into the created folder, and when I look at the readout from terminal this is what it says:

INFO:executed by python 2
INFO:importing data from scraped_data.csv
Traceback (most recent call last):
  File "image-downloader.py", line 133, in <module>
    main(sys.argv)
  File "image-downloader.py", line 125, in main
    download_csv_file_images(csv_filename)
  File "image-downloader.py", line 111, in download_csv_file_images
    with open(filename, "r", encoding="utf8") as csvfile:
TypeError: 'encoding' is an invalid keyword argument for this function

I'm on a pretty ancient mac - maybe that's the problem?
2012 Macbook Pro / MacOS Catalina 10.15.7

Please help! :)
I will go and try on my new Mac mini and see if that helps.....

**Comment by JohnnyDeadwax** [comment]
Ok - I sorted meself out.
Obvs this code is 6 years old, so some bugs would have arisen.
Eventually got things going on the MacMini M2, and the busted ass old 2012 Macbook.
Had to change "python" to "python3" in this bit of terminal code: "python image-downloader scraped_data.csv"
Then on the macbook also had to go into the downloaded Python package and open "Install Certificates.command" file which fixed some SSL cert verification doo-hickey.

All set now, and donwloading image like a mofo. Who wants to see some sexy.....Japanese audio cassettes!

[
![1699701216-1-cassetteImage](https://github.com/webscraperio/image-downloader/assets/150521220/d35e0157-78a8-40ef-8e1a-4adca1a41880)
